### ISSUE TITLE
Error Invalid device id 

### ISSUE THREAD

**Issue by 0xrushi** [ligoudaner377/font_translator_gan#7]
Hello, thanks for putting up this repo,

After following the instructions from the readme I'm getting this invalid device id error. But my torch with gpu does work
```
>>> import torch
>>> torch.cuda.current_device()
0
>>> 
```
I think there is some option for multiple GPUs which I'm not able to find

```╰─➤  bash train.sh                                                                             1 ↵
+ python train.py --dataroot ./datasets/font --model font_translator_gan --name test_new_dataset --no_dropout
----------------- Options ---------------
               batch_size: 256                           
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                 dataroot: ./datasets/font                      [default: None]
             dataset_mode: font                          
                direction: english2chinese               
                    dis_2: True                          
              display_env: main                          
             display_freq: 51200                         
               display_id: 1                             
            display_ncols: 10                            
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 64                            
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: hinge                         
                  gpu_ids: 0,1                           
                init_gain: 0.02                          
                init_type: normal                        
                  isTrain: True                                 [default: None]
                lambda_L1: 100.0                         
           lambda_content: 1.0                           
             lambda_style: 1.0                           
                load_iter: 0                                    [default: 0]
                load_size: 64                            
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: font_translator_gan           
                 n_epochs: 10                            
           n_epochs_decay: 10                            
               n_layers_D: 3                             
                     name: test_new_dataset                     [default: experiment_name]
                      ndf: 64                            
                     netD: basic_64                      
                     netG: FTGAN_MLAN                    
                      ngf: 64                            
               no_dropout: True                                 [default: False]
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                    phase: train                         
                pool_size: 0                             
               print_freq: 51200                         
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000000                       
            style_channel: 6                             
                   suffix:                               
         update_html_freq: 51200                         
        use_spectral_norm: True                          
                  verbose: False                         
----------------- End -------------------
dataset [FontDataset] was created
The number of training images = 753637
gpuids [0, 1]
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/mnt/hdd2/Documents/font_translator_gan/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/mnt/hdd2/Documents/font_translator_gan/models/font_translator_gan_model.py", line 43, in __init__
    not opt.no_dropout, opt.init_type, opt.init_gain, self.gpu_ids)
  File "/mnt/hdd2/Documents/font_translator_gan/models/networks.py", line 184, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/mnt/hdd2/Documents/font_translator_gan/models/networks.py", line 125, in init_net
    net = torch.nn.DataParallel(net, gpu_ids)  # multi-GPUs
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_utils.py", line 455, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_utils.py", line 455, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_utils.py", line 438, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_utils.py", line 455, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 312, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

**Comment by 0xrushi** [comment]
Nvm, I did found a default Id here
`parser.add_argument('--gpu_ids', type=str, default='-1', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')`

But that ends up with 

```
╰─➤  bash train.sh                                                                             1 ↵
+ python train.py --dataroot ./datasets/font --model font_translator_gan --name test_new_dataset --no_dropout
----------------- Options ---------------
               batch_size: 256                           
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                 dataroot: ./datasets/font                      [default: None]
             dataset_mode: font                          
                direction: english2chinese               
                    dis_2: True                          
              display_env: main                          
             display_freq: 51200                         
               display_id: 1                             
            display_ncols: 10                            
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 64                            
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: hinge                         
                  gpu_ids: -1                            
                init_gain: 0.02                          
                init_type: normal                        
                  isTrain: True                                 [default: None]
                lambda_L1: 100.0                         
           lambda_content: 1.0                           
             lambda_style: 1.0                           
                load_iter: 0                                    [default: 0]
                load_size: 64                            
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: font_translator_gan           
                 n_epochs: 10                            
           n_epochs_decay: 10                            
               n_layers_D: 3                             
                     name: test_new_dataset                     [default: experiment_name]
                      ndf: 64                            
                     netD: basic_64                      
                     netG: FTGAN_MLAN                    
                      ngf: 64                            
               no_dropout: True                                 [default: False]
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                    phase: train                         
                pool_size: 0                             
               print_freq: 51200                         
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000000                       
            style_channel: 6                             
                   suffix:                               
         update_html_freq: 51200                         
        use_spectral_norm: True                          
                  verbose: False                         
----------------- End -------------------
dataset [FontDataset] was created
The number of training images = 753637
initialize network with normal
initialize network with normal
initialize network with normal
model [FontTranslatorGANModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 32.068 M
[Network D_content] Total number of parameters : 0.662 M
[Network D_style] Total number of parameters : 0.667 M
-----------------------------------------------
Setting up a new session...
create web directory ./checkpoints/test_new_dataset/web...
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/mnt/hdd2/Documents/font_translator_gan/data/__init__.py", line 86, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/hdd2/Documents/font_translator_gan/data/font_dataset.py", line 54, in __getitem__
    content_image = self.load_image(content_path)
  File "/mnt/hdd2/Documents/font_translator_gan/data/font_dataset.py", line 66, in load_image
    image = self.transform(image)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/bread/anaconda3/envs/p37/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
IndexError: too many indices for tensor of dimension 0

```
